name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run own action
        id: my-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@bversteegh-xero'
      - name: Output time set in container
        run: echo "The time was ${{ steps.my-action.outputs.time }} when the action said hello"
